import {openPrintDocument} from '../core/print.js';
import {shareReceiptImage} from '../core/share-receipt.js';
const money=n=>Number(n||0).toLocaleString('vi-VN');
const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const compactOrderId=value=>{const id=String(value??'').trim();return id.length<=12?id:`#${id.slice(-4)}`;};
const dateKey=value=>{const d=value instanceof Date?new Date(value):new Date(value);if(Number.isNaN(d.getTime()))return'';const p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`;};
const fmtDate=value=>{const d=new Date(value);return Number.isNaN(d.getTime())?'':d.toLocaleString('vi-VN',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});};

export function quickRange(type,base=new Date()){
  const d=new Date(base);d.setHours(12,0,0,0);let from=new Date(d),to=new Date(d);
  if(type==='yesterday'){from.setDate(from.getDate()-1);to=new Date(from);}else if(type==='week'){const day=d.getDay(),delta=day===0?-6:1-day;from.setDate(d.getDate()+delta);to=new Date(from);to.setDate(from.getDate()+6);}else if(type==='month'){from=new Date(d.getFullYear(),d.getMonth(),1,12);to=new Date(d.getFullYear(),d.getMonth()+1,0,12);}else if(type==='year'){from=new Date(d.getFullYear(),0,1,12);to=new Date(d.getFullYear(),11,31,12);}return {from:dateKey(from),to:dateKey(to)};
}

export function filterDeliveredOrders(orders=[],filter={}){
  const mode=filter.mode||'today',from=filter.from||dateKey(new Date()),to=filter.to||from;
  return orders.filter(o=>{if(o.trangThai!=='done'&&o.status!=='done')return false;const dk=dateKey(o.ngay||o.ordered_at);if(mode==='today'&&dk!==dateKey(new Date(from+'T12:00:00')))return false;if(mode==='range'&&(dk<from||dk>to))return false;return true;}).sort((a,b)=>new Date(b.ngay||b.ordered_at)-new Date(a.ngay||a.ordered_at));
}

export function summarizeDeliveredBySource(orders=[]){
  const map=new Map();let total={qty:0,cost:0,revenue:0,profit:0};
  for(const order of orders)for(const item of order.items||[]){const source=item.nhom||item.product_group||'Khác',qty=Number(item.sl??item.qty)||0,price=Number(item.gia??item.unit_price)||0,costUnit=Number(item.von??item.unit_cost)||0;const row=map.get(source)||{source,qty:0,cost:0,revenue:0,profit:0};row.qty+=qty;row.cost+=costUnit*qty;row.revenue+=price*qty;row.profit+=(price-costUnit)*qty;map.set(source,row);total.qty+=qty;total.cost+=costUnit*qty;total.revenue+=price*qty;total.profit+=(price-costUnit)*qty;}
  return {rows:[...map.values()].sort((a,b)=>b.revenue-a.revenue||a.source.localeCompare(b.source,'vi')),total};
}

function summaryMarkup(orders,canViewCost){
  const s=summarizeDeliveredBySource(orders);
  if(!s.rows.length)return '<tr><td colspan="5" class="text-center py-4 text-gray-400">Không có dữ liệu</td></tr>';
  if(!canViewCost)return `${s.rows.map(r=>`<tr class="border-b border-gray-50"><td class="py-3 font-bold text-gray-800">${esc(r.source)}</td><td class="py-3 text-right font-bold text-gray-600">${r.qty}</td><td class="py-3 text-right font-bold text-success">${money(r.revenue)}</td></tr>`).join('')}<tr class="summary-total-row font-extrabold text-gray-800"><td class="py-3 pl-1">TỔNG</td><td class="py-3 text-right">${s.total.qty}</td><td class="py-3 text-right text-success">${money(s.total.revenue)}</td></tr>`;
  return `${s.rows.map(r=>`<tr class="border-b border-gray-50 hover:bg-gray-50/50"><td class="py-3 font-bold text-gray-800">${esc(r.source)}</td><td class="py-3 text-right font-bold text-gray-600">${r.qty}</td><td class="py-3 text-right font-bold text-gray-500 pr-2">${money(r.cost)}</td><td class="py-3 text-right font-bold text-success pr-2">${money(r.revenue)}</td><td class="py-3 text-right font-bold text-success pr-2">${money(r.profit)}</td></tr>`).join('')}<tr class="summary-total-row font-extrabold text-gray-800"><td class="py-3 pl-1">TỔNG</td><td class="py-3 text-right">${s.total.qty}</td><td class="py-3 text-right text-gray-500 pr-2">${money(s.total.cost)}</td><td class="py-3 text-right text-success pr-2">${money(s.total.revenue)}</td><td class="py-3 text-right text-success pr-2">${money(s.total.profit)}</td></tr>`;
}

function orderCard(o,index,canViewCost,totalCount){
  const items=o.items||[],qty=items.reduce((a,x)=>a+(Number(x.sl??x.qty)||0),0),profit=Number(o.loiNhuan??(Number(o.tongTien||0)-Number(o.tongVon||0)))||0,codes=items.length||Number(o.tongMa)||0,totalQty=qty||Number(o.tongSL)||0;
  return `<button class="fixed-order-card rounded-[16px] p-3.5 shadow-sm flex justify-between items-center mb-3 transition" type="button" data-order-open="${esc(o.id)}"><div class="pointer-events-none flex items-center gap-3 min-w-0"><div class="w-9 h-9 rounded-full bg-green-50 text-success font-extrabold text-sm flex items-center justify-center shrink-0">${Math.max(1,totalCount-index)}</div><div class="min-w-0"><p class="font-bold text-[14px] text-gray-600 truncate"><span class="text-success font-extrabold">${esc(compactOrderId(o.id))}</span> - ${esc(o.tenKH||'Khách lẻ')}</p><p class="text-[11px] text-gray-400 mt-0.5">${codes} mã - ${totalQty} SP | ${esc(fmtDate(o.ngay||o.ordered_at))}</p></div></div><div class="pointer-events-none text-right shrink-0 pl-3"><p class="font-extrabold text-[15px] text-gray-900">${money(o.tongTien)}</p>${canViewCost?`<p class="text-[11px] font-bold text-success mt-0.5">+${money(profit)}</p>`:''}</div></button>`;
}

function detailMarkup(o,{canViewCost=false,canManageOrders=false}={}){const items=o.items||[],qty=items.reduce((a,x)=>a+(Number(x.sl??x.qty)||0),0),profit=Number(o.loiNhuan??(Number(o.tongTien||0)-Number(o.tongVon||0)))||0;return `<div class="delivered-overlay" data-order-detail><button class="delivered-backdrop" type="button" data-detail-close aria-label="Đóng"></button><section class="delivered-detail-panel ui-popup-l1"><header class="ui-popup-header"><strong>Đơn đã giao</strong><span class="ui-status ui-status-success">Đã giao</span><div class="ui-action-group"><button class="ui-action ui-action-secondary" type="button" data-receipt-share>Chia sẻ ảnh</button><button class="ui-icon-button" type="button" data-detail-close aria-label="Đóng chi tiết"></button></div></header><div class="classic-receipt" data-receipt-capture><div class="delivered-detail-meta"><b>KH: ${esc(o.tenKH)}</b> · ${esc(compactOrderId(o.id))} · ${esc(fmtDate(o.ngay))}</div><div class="delivered-detail-head classic-detail-table ui-table-head"><span>#</span><span>TÊN</span><span>SL</span><span>Đ.GIÁ</span><span>T.TIỀN</span></div><div class="delivered-detail-lines classic-detail-table ui-table">${items.map((it,i)=>`<div class="delivered-detail-line ui-row"><span>${i+1}.</span><span>${esc(it.tenSP||it.ten||'')}${it.ghiChu?`<small>${esc(it.ghiChu)}</small>`:''}</span><span>${it.sl??it.qty??0}</span><span>${money(it.gia??it.unit_price)}</span><strong>${money((Number(it.gia??it.unit_price)||0)*(Number(it.sl??it.qty)||0))}</strong></div>`).join('')}</div><div class="delivered-detail-total ui-summary"><b>Tổng ${qty} SP</b><span><strong>${money(o.tongTien)}</strong>${canViewCost?`<small>Lãi +${money(profit)}</small>`:''}</span></div></div><footer class="ui-action-group">${canManageOrders?'<button class="ui-action ui-action-secondary" type="button" data-detail-action="edit">Sửa</button>':''}<button class="ui-action ui-action-secondary" type="button" data-detail-action="print">In</button>${canManageOrders?'<button class="ui-action ui-action-danger" type="button" data-detail-action="delete">Xoá</button>':''}</footer></section></div>`;}
function deliveredPrintBody(o){const items=o.items||[];return `<main class="print-sheet"><div class="print-head">Đơn đã giao · ${esc(compactOrderId(o.id))}</div><div class="print-meta"><b>KH: ${esc(o.tenKH)}</b> · ${esc(fmtDate(o.ngay))}</div>${items.map((it,i)=>`<div class="print-row"><span>${i+1}. ${esc(it.tenSP||it.ten||'')}</span><span>${it.sl??it.qty??0} × ${money(it.gia??it.unit_price)}</span></div>`).join('')}<div class="print-total"><span>Tổng</span><strong>${money(o.tongTien)}</strong></div></main>`;}
function printMarkup(o){const items=o.items||[];return `<div class="delivered-overlay delivered-print-overlay"><button class="delivered-backdrop" type="button" data-print-close aria-label="Đóng"></button><section class="delivered-print-panel ui-popup-l2"><header class="ui-popup-header"><strong>Đơn đã giao</strong><div class="ui-action-group"><button class="ui-action ui-action-primary" type="button" data-print-now>In</button><button class="ui-icon-button" type="button" data-print-close aria-label="Đóng bản in"></button></div></header><div class="delivered-print-meta"><b>KH: ${esc(o.tenKH)}</b><span>${esc(compactOrderId(o.id))} · ${esc(fmtDate(o.ngay))}</span></div><div class="delivered-print-lines ui-table">${items.map((it,i)=>`<div class="ui-row"><span>${i+1}. ${esc(it.tenSP||it.ten||'')}</span><span>${it.sl??it.qty??0} × ${money(it.gia??it.unit_price)}</span></div>`).join('')}</div><div class="delivered-print-total ui-summary"><b>Tổng</b><strong>${money(o.tongTien)}</strong></div></section></div>`;}
function calendarMarkup(state){if(!state.calendarOpen)return'';const base=new Date((state.calendarMonth||state.from)+'T12:00:00'),y=base.getFullYear(),m=base.getMonth(),first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate();let cells='';for(let i=0;i<first;i++)cells+='<span></span>';for(let d=1;d<=days;d++){const key=dateKey(new Date(y,m,d,12)),selected=key===state.from||key===state.to;cells+=`<button type="button" data-calendar-day="${key}" aria-pressed="${selected}">${d}</button>`;}return `<div class="delivered-calendar"><div class="delivered-calendar-nav"><button class="ui-icon-button" type="button" data-month="-1" aria-label="Tháng trước"></button><b>${y} / ${String(m+1).padStart(2,'0')}</b><button class="ui-icon-button" type="button" data-month="1" aria-label="Tháng sau"></button></div><div class="delivered-week"><span>CN</span><span>T2</span><span>T3</span><span>T4</span><span>T5</span><span>T6</span><span>T7</span></div><div class="delivered-days">${cells}</div><div class="delivered-quick"><button type="button" data-quick="yesterday">Hôm qua</button><button type="button" data-quick="week">Tuần này</button><button type="button" data-quick="month">Tháng này</button><button type="button" data-quick="year">Năm nay</button></div><div class="delivered-calendar-close"><span>${state.picking==='to'?'Chọn ngày kết thúc':'Chọn ngày bắt đầu'}</span><button type="button" data-calendar-close>Đóng</button></div></div>`;}

export function deliveredMarkup(input={}){
  const today=dateKey(new Date()),state={orders:[],mode:'today',from:today,to:today,calendarOpen:false,calendarMonth:today,picking:'from',selected:null,printOrder:null,permissions:{},...input},done=filterDeliveredOrders(state.orders,state),canViewCost=state.permissions?.canViewCost===true,canManageOrders=state.permissions?.canManageOrders===true;
  const label=state.mode==='today'?'Hôm nay':(state.from===state.to?`${state.from.slice(8,10)}/${state.from.slice(5,7)}`:`${state.from.slice(8,10)}/${state.from.slice(5,7)} → ${state.to.slice(8,10)}/${state.to.slice(5,7)}`);
  return `<section class="fixed-order-screen" data-screen-id="delivered" data-ui-source="TAPHOA_GEMINI_100_SAMPLE_FIXED"><header class="bg-[#1e293b] px-4 py-3.5 flex justify-between items-center gap-3 shrink-0 rounded-b-[20px] shadow-sm z-20 relative"><div class="min-w-0"><div class="flex items-center gap-2.5"><span class="text-white font-bold text-[15px]">Đơn hàng đã giao</span><span class="bg-white/20 text-white text-[11px] font-bold px-2.5 py-0.5 rounded-lg">${done.length}</span></div><div class="text-[10px] text-slate-300 mt-1 truncate">${esc(label)}</div></div><div class="relative shrink-0"><button class="h-9 px-3 rounded-xl bg-white/10 border border-white/10 text-white text-[11px] font-bold flex items-center gap-1.5 hover:bg-white/15 transition" data-calendar-toggle type="button"><i class="ph ph-calendar-blank text-[13px]"></i><span>${esc(label)}</span><i class="ph ph-caret-down text-[10px] text-white/60"></i></button>${calendarMarkup(state)}</div></header><main class="fixed-order-main p-4 space-y-5 no-scrollbar pb-20"><div class="bg-white rounded-2xl p-4 shadow-sm border border-gray-100"><div class="flex justify-between items-center mb-4"><h3 class="text-[11px] font-bold text-gray-400 uppercase tracking-wider">Tổng hợp đơn đã giao theo nguồn sản phẩm</h3><i class="ph ph-chart-bar text-success text-lg"></i></div><div class="overflow-x-auto"><table class="summary-compact-table w-full text-left text-xs"><thead><tr class="border-b border-gray-100 pb-2"><th class="pb-2 font-semibold text-gray-700">Nguồn</th><th class="pb-2 text-right font-semibold text-gray-400">SL</th>${canViewCost?'<th class="pb-2 text-right font-semibold text-gray-500 pr-2">Chi</th>':''}<th class="pb-2 text-right font-semibold text-success pr-2">Thu</th>${canViewCost?'<th class="pb-2 text-right font-semibold text-success pr-2">Lãi</th>':''}</tr></thead><tbody>${summaryMarkup(done,canViewCost)}</tbody></table></div></div><div><h3 class="text-[11px] font-bold text-gray-400 uppercase tracking-wider mb-3">Danh sách chi tiết đơn đã giao</h3><div>${done.map((order,index)=>orderCard(order,index,canViewCost,done.length)).join('')||'<p class="text-center text-gray-400 mt-4 text-xs">Không có đơn đã giao trong khoảng thời gian này</p>'}</div></div></main>${state.selected?detailMarkup(state.selected,{canViewCost,canManageOrders}):''}${state.printOrder?printMarkup(state.printOrder):''}</section>`;
}

export async function mount(context){
  const root=context.root,today=dateKey(new Date()),data=()=>context.getData?.()||context.data||{};let busy=false,state={orders:data().orders||[],permissions:data().permissions||{},mode:'today',from:today,to:today,calendarOpen:false,calendarMonth:today,picking:'from',selected:null,printOrder:null};
  const canManage=()=>state.permissions?.canManageOrders===true,render=()=>{const current=data();state={...state,orders:current.orders||state.orders,permissions:current.permissions||state.permissions};root.innerHTML=deliveredMarkup(state);},unsubscribeData=context.subscribeData?.(({changed})=>{if(changed.some(x=>x==='bootstrap'||x==='orders'||x==='products'||x==='customers'))render();}),findOrder=id=>state.orders.find(o=>String(o.id)===String(id));
  const onClick=async event=>{if(event.target.closest('[data-calendar-toggle]')){state={...state,calendarOpen:!state.calendarOpen,picking:'from',calendarMonth:state.from};render();return;}if(event.target.closest('[data-calendar-close]')){state={...state,calendarOpen:false};render();return;}const quick=event.target.closest('[data-quick]');if(quick){const r=quickRange(quick.dataset.quick);state={...state,mode:'range',from:r.from,to:r.to,calendarOpen:false,picking:'from'};render();return;}const month=event.target.closest('[data-month]');if(month){const d=new Date(state.calendarMonth+'T12:00:00');d.setMonth(d.getMonth()+Number(month.dataset.month));state={...state,calendarMonth:dateKey(d)};render();return;}const day=event.target.closest('[data-calendar-day]');if(day){const key=day.dataset.calendarDay;if(state.picking==='from')state={...state,mode:'range',from:key,to:key,picking:'to'};else state={...state,mode:'range',from:key<state.from?key:state.from,to:key<state.from?state.from:key,picking:'from',calendarOpen:false};render();return;}const open=event.target.closest('[data-order-open]');if(open){state={...state,selected:findOrder(open.dataset.orderOpen)};render();return;}if(event.target.closest('[data-detail-close]')){state={...state,selected:null};render();return;}if(event.target.closest('[data-print-close]')){state={...state,printOrder:null};render();return;}if(event.target.closest('[data-print-now]')){if(state.printOrder)openPrintDocument({title:state.printOrder.id,body:deliveredPrintBody(state.printOrder)});return;}if(event.target.closest('[data-receipt-share]')&&state.selected){try{const receipt=root.querySelector('[data-receipt-capture]');await shareReceiptImage(receipt,{fileName:`don-${state.selected.id}.jpg`,title:`Đơn hàng ${state.selected.id}`,text:`taphoa.xyz - ${state.selected.tenKH||''}`});}catch(error){context.system?.toast(error?.message||'Không chia sẻ được ảnh');}return;}const action=event.target.closest('[data-detail-action]')?.dataset.detailAction;if(!action||!state.selected)return;if(action==='print'){state={...state,printOrder:state.selected,selected:null};render();return;}if(!canManage())return;if(action==='edit'){try{const detail=await context.business.orderDetail(state.selected.id);context.editOrder?.(detail?.order||state.selected);context.navigate?.('sales');}catch(e){context.system?.toast(e?.message||'Không thực hiện được');}return;}if(action==='delete'){if(busy||!window.confirm(`Xoá đơn ${state.selected.id}?`))return;busy=true;try{await context.business.reverseOrder(state.selected.id,'Hoàn đơn');await context.refresh?.(['orders','debt']);state={...state,selected:null};render();}catch(e){context.system?.toast(e?.message||'Không thực hiện được');}finally{busy=false;}}};
  root.addEventListener('click',onClick);render();return()=>{unsubscribeData?.();root.removeEventListener('click',onClick);};
}
