import {readFile,readdir,mkdir,writeFile,copyFile} from 'node:fs/promises';
import {gunzipSync} from 'node:zlib';
import {createHash} from 'node:crypto';
import path from 'node:path';
const ROOT=process.cwd(), PART=path.join(ROOT,'backups','v1.27','parts'), DIST=path.join(ROOT,'dist');
const files=(await readdir(PART)).filter(x=>/^TAPHOA_SUPABASE_V1_27\.html\.gz\.b64\.part\d+$/.test(x)).sort();
if(files.length!==12) throw Error(`Expected 12 V1.27 parts, found ${files.length}`);
let html=gunzipSync(Buffer.from((await Promise.all(files.map(f=>readFile(path.join(PART,f),'utf8')))).join(''),'base64')).toString('utf8');
const oldSha=createHash('sha256').update(html).digest('hex');
if(oldSha!=='12d1cbe2dbf8f32507c8044329c52c5ab3b042b898af7c5481286931a047a983') throw Error(`V1.27 SHA mismatch ${oldSha}`);
html=html.replace(/const SHOP_LOGO_DATA='data:image\/jpeg;base64,[^']+';/,"const SHOP_LOGO_SRC='./src/assets/logo.jpg';").replaceAll('SHOP_LOGO_DATA','SHOP_LOGO_SRC');
const theme='  <meta name="theme-color" content="#1565C0"/>';
html=html.replace(theme,theme+'\n  <meta name="apple-mobile-web-app-title" content="taphoa.xyz"/>\n  <link rel="icon" type="image/jpeg" href="./src/assets/logo.jpg"/>\n  <link rel="apple-touch-icon" href="./src/assets/logo.jpg"/>\n  <link rel="manifest" href="./manifest.webmanifest"/>');
const a0=html.indexOf('function Avatar({user={},size=36,style:st={},onClick}){'), a1=html.indexOf('/* ── SellerTabs',a0);
if(a0<0||a1<0) throw Error('Avatar section not found');
const avatar=`function Avatar({user={},size=36,style:st={},onClick}){\n  const raw=user.avatar||avatarCache.get(user.id||'')||'';\n  const av=EMOJI_AVATARS.includes(raw)?raw:'';\n  const isEmoji=Boolean(av),bg=getAvatarColor(user.id||user.ten||'');\n  return <div onClick={onClick} style={{width:size,height:size,borderRadius:'50%',flexShrink:0,display:'flex',alignItems:'center',justifyContent:'center',background:isEmoji?'#EEF2FF':bg,fontSize:isEmoji?size*0.56:size*0.38,fontWeight:800,color:'white',letterSpacing:-0.5,cursor:onClick?'pointer':'default',boxShadow:'0 1px 4px rgba(0,0,0,0.15)',userSelect:'none',...st}}>{isEmoji?av:getInitials(user.ten)}</div>;\n}\nfunction AvatarPicker({current,onSelect,onClose}){\n  const selected=EMOJI_AVATARS.includes(current)?current:'';\n  return <Modal onClose={onClose}><ModalHeader title="🎨 Chọn avatar" onClose={onClose}/><div style={{fontSize:12,color:C.textMuted,fontWeight:600,marginBottom:8}}>Chọn emoji:</div><div style={{display:'grid',gridTemplateColumns:'repeat(6,1fr)',gap:6,marginBottom:14}}>{EMOJI_AVATARS.map(e=><button key={e} onClick={()=>onSelect(e)} style={{fontSize:26,background:selected===e?C.blueLight:'transparent',border:\`2px solid \${selected===e?C.blue:'transparent'}\`,borderRadius:10,padding:'5px 0',cursor:'pointer',display:'flex',alignItems:'center',justifyContent:'center',transform:selected===e?'scale(1.15)':'scale(1)',transition:'all 0.15s'}}>{e}</button>)}</div><Btn onClick={()=>onSelect('')} outline color={C.textSec} full>🔄 Dùng chữ cái tên</Btn></Modal>;\n}\n\n`;
html=html.slice(0,a0)+avatar+html.slice(a1);
html=html.replace('>📷</div>','>✏️</div>');
html=html.replace('{currentUser.avatar?.startsWith("data:")?"Ảnh từ máy":currentUser.avatar?"Emoji":"Chữ cái tên"}','{EMOJI_AVATARS.includes(currentUser.avatar)?"Emoji":"Chữ cái tên"}');
const end='</button>\n      </div>\n    </div>\n  );\n}\n\nconst avatarCache=';
if(!html.includes(end)) throw Error('CustomerProfile end marker not found');
html=html.replace(end,'</button>\n      </div>\n      {showPicker&&<AvatarPicker current={currentUser.avatar||""} onSelect={saveAvatar} onClose={()=>setShowPicker(false)}/>}\n    </div>\n  );\n}\n\nconst avatarCache=');
html=html.replace('taphoa_ui_cache_v27_','taphoa_ui_cache_v28_');
for(const bad of ['data:image','FileReader','readAsDataURL','toDataURL','type="file"','file://','SHOP_LOGO_DATA','startsWith("data:")']) if(html.includes(bad)) throw Error(`Forbidden V1.28 token: ${bad}`);
if(!html.includes('https://gcnoahqsrquxkwkjbuxy.supabase.co/functions/v1/taphoa-api')) throw Error('Supabase HTTPS endpoint missing');
if((html.match(/api\.call\("/g)||[]).length!==29) throw Error('Business API call count changed');
const out=Buffer.from(html), sha=createHash('sha256').update(out).digest('hex');
if(out.length!==186726) throw Error(`V1.28 bytes ${out.length} != 186726`);
if(sha!=='f64eaf795d07654a90b3736c988fb05c9d2e2f9df2bfa64173cdd93c5cf1e40a') throw Error(`V1.28 SHA mismatch ${sha}`);
await mkdir(path.join(DIST,'src','assets'),{recursive:true});
await writeFile(path.join(DIST,'index.html'),out); await copyFile(path.join(ROOT,'manifest.webmanifest'),path.join(DIST,'manifest.webmanifest')); await copyFile(path.join(ROOT,'src','assets','logo.jpg'),path.join(DIST,'src','assets','logo.jpg'));
console.log(`BUILD PASS V1.28 ${out.length} ${sha}`);
