import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
const file='dist/index.html';
let html=await readFile(file,'utf8');
const inputSha=createHash('sha256').update(Buffer.from(html)).digest('hex');
if(inputSha!=='f64eaf795d07654a90b3736c988fb05c9d2e2f9df2bfa64173cdd93c5cf1e40a') throw Error(`V1.28 SHA mismatch ${inputSha}`);
const replace=(a,b,label)=>{if(!html.includes(a))throw Error(`Missing V1.29 patch target: ${label}`);html=html.replace(a,b);};
replace('function Inp({value,onChange,placeholder,type="text",style:st={},pfx,onKeyDown,onFocus,onClick}){','function Inp({value,onChange,placeholder,type="text",style:st={},pfx,onKeyDown,onFocus,onClick,autoComplete}){','Inp signature');
replace('<input value={value} onChange={e=>onChange(e.target.value)} onKeyDown={onKeyDown} onFocus={onFocus} onClick={onClick} type={type} placeholder={placeholder}','<input value={value} onChange={e=>onChange(e.target.value)} onKeyDown={onKeyDown} onFocus={onFocus} onClick={onClick} type={type} autoComplete={autoComplete} placeholder={placeholder}','Inp autocomplete');
replace('const res=await api.call("login",{username:u.trim(),password:p,remember:rememberMe});','const res=await api.call("login",{username:u.trim(),password:p,remember:false});','short login session');
replace('<Inp value={u} onChange={v=>{setU(v);setErr("");}} placeholder="Tên đăng nhập" pfx="👤"/>','<Inp value={u} onChange={v=>{setU(v);setErr("");}} placeholder="Tên đăng nhập" pfx="👤" autoComplete="off"/>','username autocomplete');
replace('<Inp value={p} onChange={v=>{setP(v);setErr("");}} onKeyDown={e=>e.key==="Enter"&&login()} placeholder="Mật khẩu" type={showP?"text":"password"} pfx="🔑"/>','<Inp value={p} onChange={v=>{setP(v);setErr("");}} onKeyDown={e=>e.key==="Enter"&&login()} placeholder="Mật khẩu" type={showP?"text":"password"} pfx="🔑" autoComplete="off"/>','password autocomplete');
replace('Ghi nhớ đăng nhập</label>','Ghi nhớ tên đăng nhập</label>','remember label');
replace('const readTaphoaSession=()=>{try{return JSON.parse(sessionStorage.getItem("taphoa_session")||localStorage.getItem("taphoa_session")||"null");}catch{return null;}};','const readTaphoaSession=()=>{try{localStorage.removeItem("taphoa_session");return JSON.parse(sessionStorage.getItem("taphoa_session")||"null");}catch{return null;}};','session read');
replace('const storeSession=(s,remember)=>{clearTaphoaSession();if(!s)return;try{(remember?localStorage:sessionStorage).setItem("taphoa_session",JSON.stringify(s));}catch{}};','const storeSession=(s)=>{clearTaphoaSession();if(!s)return;try{sessionStorage.setItem("taphoa_session",JSON.stringify(s));}catch{}};','session store');
replace('setSessionRaw(s);storeSession(s,remember);setTab(auth.user.loai==="seller"?"sell":"shop");','setSessionRaw(s);storeSession(s);setTab(auth.user.loai==="seller"?"sell":"shop");','login storage');
replace('try{if(localStorage.getItem("taphoa_session"))localStorage.setItem("taphoa_session",JSON.stringify(next));else sessionStorage.setItem("taphoa_session",JSON.stringify(next));}catch{}','try{sessionStorage.setItem("taphoa_session",JSON.stringify(next));localStorage.removeItem("taphoa_session");}catch{}','session update');
replace('taphoa_ui_cache_v28_','taphoa_ui_cache_v29_','cache namespace');
replace('if(!form.ten||!form.username||!form.password){notify("⚠️ Nhập đầy đủ!");return;}if(customers.find','if(!form.ten||!form.username||!form.password){notify("⚠️ Nhập đầy đủ!");return;}if(form.password.length<8){notify("⚠️ Mật khẩu cần ít nhất 8 ký tự!");return;}if(customers.find','new customer password');
replace('if(customers.some(c=>c.id!==editKH.id&&String(c.username||"").toLowerCase()===username.toLowerCase())){notify("⚠️ Tên đăng nhập đã tồn tại!");return;}setBusySave(true);','if(customers.some(c=>c.id!==editKH.id&&String(c.username||"").toLowerCase()===username.toLowerCase())){notify("⚠️ Tên đăng nhập đã tồn tại!");return;}if(editPassword&&editPassword.length<8){notify("⚠️ Mật khẩu cần ít nhất 8 ký tự!");return;}setBusySave(true);','changed customer password');
replace('<Inp value={editPassword} onChange={setEditPassword} placeholder="Nhập mật khẩu mới" type="password"/>','<Inp value={editPassword} onChange={setEditPassword} placeholder="Nhập mật khẩu mới" type="password" autoComplete="new-password"/>','edit password autocomplete');
replace('<Inp value={form[k]} onChange={v=>setForm(f=>({...f,[k]:v}))} placeholder={lb} type={t}/>','<Inp value={form[k]} onChange={v=>setForm(f=>({...f,[k]:v}))} placeholder={lb} type={t} autoComplete={t==="password"?"new-password":undefined}/>','new password autocomplete');
const forbidden=['localStorage.getItem("taphoa_session")','localStorage.setItem("taphoa_session"','Ghi nhớ đăng nhập'];
for(const x of forbidden)if(html.includes(x))throw Error(`Forbidden V1.29 token: ${x}`);
if((html.match(/api\.call\("/g)||[]).length!==29)throw Error('Business API call count changed');
if(!html.includes('https://gcnoahqsrquxkwkjbuxy.supabase.co/functions/v1/taphoa-api'))throw Error('Supabase HTTPS endpoint changed');
const out=Buffer.from(html),sha=createHash('sha256').update(out).digest('hex');
if(out.length!==186984)throw Error(`V1.29 bytes ${out.length} != 186984`);
if(sha!=='55d1d4696a93a5fa1eb8ff926c8b658258769a08b8699b62bc0b96c251e43b0d')throw Error(`V1.29 SHA mismatch ${sha}`);
await writeFile(file,out);
console.log(`HARDEN PASS V1.29 ${out.length} ${sha}`);
