import {readFile} from "node:fs/promises";
import {createHash} from "node:crypto";
const html=await readFile("dist/index.html","utf8");
const b=Buffer.from(html),sha=createHash("sha256").update(b).digest("hex");
const req=(cond,msg)=>{if(!cond)throw Error(msg)};
req(b.length===216232,`bytes ${b.length}`);
req(sha==="ae5425fb06f12b6a93ea00f1960381e69a649e64d8c8b6315946990ed469f84d",`sha ${sha}`);
req((html.match(/api\.call\("/g)||[]).length===29,"API call count changed");
const p=html.indexOf("function ReportHubScreen("),q=html.indexOf("/* ── CUSTOMERS TAB",p),r=html.slice(p,q);
req(r.includes("Bán hàng")&&r.includes("Lãi lỗ")&&r.includes("Sản phẩm")&&r.includes("Thu chi"),"report tabs missing");
req(!r.includes("Kho hàng"),"Kho hàng must be removed");
req(r.includes("report-full-table-scroll"),"bounded full table scroll missing");
req(r.includes("report-detail-overlay"),"table detail overlay missing");
req(r.includes("axis-money")&&r.includes("axis-time"),"chart axes missing");
req(r.includes("Tổng thu")&&r.includes("Tổng chi")&&r.includes("Chênh lệch"),"cash summary missing");
req(!html.includes('localStorage.setItem("taphoa_session"')&&!html.includes('localStorage.getItem("taphoa_session"'),"session hardening regressed");
console.log(`TEST PASS V1.33 ${b.length} ${sha}`);
